[tool.poetry]
name = "rotsim2d"
version = "0.1.0"
description = "Simulate 2D rovibrational spectra of gas-phase molecular samples"
authors = ["Grzegorz Kowzan <grzegorz@kowzan.eu>"]
readme = "README.md"
homepage = "https://gitlab.com/allisonlab/mdcs/rotsim2d"
repository = "https://gitlab.com/allisonlab/mdcs/rotsim2d"
classifiers=[
	'Development Status :: 3 - Alpha',
        'Environment :: Console',
        'Intended Audience :: Science/Research',
        'Topic :: Scientific/Engineering :: Physics']
include = ['README.md']

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
numpy = "^1.20.1"
scipy = "^1.6.2"
anytree = "^2.8.0"
sympy = "^1.8"
pywigxjpf = {git = "ssh://git@gitlab.com/allisonlab/mdcs/pywigxjpf.git", rev = "master"}
shed = {git = "ssh://git@gitlab.com/allisonlab/mdcs/shed.git", rev = "master"}
spectroscopy = {git = "ssh://git@gitlab.com/allisonlab/mdcs/spectroscopy.git", rev = "master"}
matplotlib = {version = "^3.3.4", optional = true}
ipython = {version = "^7.21.0", optional = true}
PyQt5 = {version = "^5.15.4", optional = true}
Sphinx = {version = "^3.5.4", optional = true}
sphinx-rtd-theme = {version = "^0.5.2", optional = true}
numpydoc = {version = "^1.1.0", optional = true}

[tool.poetry.extras]
interactive = ["matplotlib", "ipython", "PyQt5"]
doc = ["Sphinx", "sphinx_rtd_theme", "numpydoc"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
